// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RestaurantIdImport } from './routes/$restaurantId'

// Create/Update Routes

const RestaurantIdRoute = RestaurantIdImport.update({
  path: '/$restaurantId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$restaurantId': {
      preLoaderRoute: typeof RestaurantIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([RestaurantIdRoute])
